"""Generates src/core/PinyinTable.cpp from the pinyin-data files in tools/data.

pinyin-data (https://github.com/mozillazg/pinyin-data, MIT licence, see
tools/data/pinyin-data-LICENSE.txt) provides:
  pinyin.txt      every reading found in several dictionaries, most common first
  kTGHZ2013.txt   the readings of the 8105 characters in the 2013 standard
                  《通用规范汉字字典》, without the rare and historic ones

For each character in CJK Unified Ideographs (U+4E00-U+9FFF, which covers
the Chinese file names on a typical disk) the table keeps, without tones:
  - characters in the standard: their standard readings, most common first
    (at most three); so 胶 is only "jiao", but 行 is "xing" and "hang"
  - other (rare) characters: their most common reading
ü is written v, as pinyin keyboards do ("lv" for 绿).

Usage: python tools/make_pinyin.py
"""
import pathlib
import re
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "tools" / "data"
OUTPUT = ROOT / "src" / "core" / "PinyinTable.cpp"

FIRST, LAST = 0x4E00, 0x9FFF
MAX_READINGS = 3
BITS = 10  # per reading: syllable number + 1, 0 = none
DIAERESIS = "̈"


def toneless(reading):
    """'lǜ' -> 'lv', 'zhāng' -> 'zhang', 'ê̄' -> 'e'."""
    out = []
    for ch in unicodedata.normalize("NFD", reading):
        if ch == DIAERESIS and out and out[-1] == "u":
            out[-1] = "v"  # ü
        elif unicodedata.category(ch) != "Mn":
            out.append(ch)
    syllable = "".join(out)
    if not re.fullmatch(r"[a-z]+", syllable):
        raise SystemExit(f"unexpected reading {reading!r}")
    return syllable


def load(name):
    """{code point: [toneless readings, in file order, distinct]}"""
    table = {}
    line_re = re.compile(r"^U\+([0-9A-F]+):\s*([^#]+)")
    for line in (DATA / name).read_text(encoding="utf-8").splitlines():
        m = line_re.match(line)
        if not m:
            continue
        code = int(m.group(1), 16)
        if not FIRST <= code <= LAST:
            continue
        found = []
        for reading in m.group(2).strip().split(","):
            syllable = toneless(reading.strip())
            if syllable not in found:
                found.append(syllable)
        table[code] = found
    return table


def readings():
    common = load("pinyin.txt")
    standard = load("kTGHZ2013.txt")
    table = {}
    for code, ordered in common.items():
        if code in standard:
            allowed = standard[code]
            chosen = [s for s in ordered if s in allowed] + [s for s in allowed if s not in ordered]
            table[code] = chosen[:MAX_READINGS]
        else:
            table[code] = ordered[:1]
    return table


def main():
    table = readings()
    syllables = sorted({s for found in table.values() for s in found})
    assert len(syllables) < (1 << BITS) - 1
    number = {s: i + 1 for i, s in enumerate(syllables)}

    packed = []
    initials = []
    for code in range(FIRST, LAST + 1):
        value = 0
        bits = 0
        for k, s in enumerate(table.get(code, [])):
            value |= number[s] << (BITS * k)
            bits |= 1 << (ord(s[0]) - ord("a"))
        packed.append(value)
        initials.append(bits)

    def array(kind, name, values):
        lines = [f"const {kind} {name}[{len(values)}] = {{"]
        for i in range(0, len(values), 12):
            lines.append("    " + ", ".join(f"0x{v:X}" for v in values[i:i + 12]) + ",")
        lines.append("};")
        return lines

    out = [
        "// Generated by tools/make_pinyin.py from pinyin-data",
        "// (https://github.com/mozillazg/pinyin-data, MIT licence). Do not edit.",
        '#include "Pinyin.h"',
        "",
        "namespace ws::pinyin::detail {",
        "",
        f"const std::size_t kSyllableCount = {len(syllables)};",
        f"const std::string_view kSyllables[{len(syllables)}] = {{",
    ]
    for i in range(0, len(syllables), 12):
        out.append("    " + ", ".join(f'"{s}"' for s in syllables[i:i + 12]) + ",")
    out.append("};")
    out.append("")
    out.append(f"// U+{FIRST:04X}..U+{LAST:04X}: up to {MAX_READINGS} readings, {BITS} bits each"
               " (syllable number + 1, 0 = none), most common first.")
    out += array("std::uint32_t", "kReadings", packed)
    out.append("")
    out.append("// The first letters of each character's readings, as bits (a = bit 0).")
    out += array("std::uint32_t", "kInitials", initials)
    out.append("")
    out.append("} // namespace ws::pinyin::detail")
    OUTPUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    several = sum(1 for found in table.values() if len(found) > 1)
    print(f"{OUTPUT.name}: {len(syllables)} syllables, {len(table)} characters, {several} with several readings")


if __name__ == "__main__":
    main()
